name: Generate full docs.json

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate docs.json recursively
        run: |
          echo '{' > docs.json
          first=1
          find . -type f \( -iname "*.pdf" -o -iname "*.ppt" -o -iname "*.pptx" \) | while read -r file; do
            relpath="${file#./}"
            dirname=$(dirname "$relpath")
            filename=$(basename "$file")
            url="https://harnitya29.github.io/sem3/$relpath"
            key="${dirname//\//_}"

            if grep -q "\"$key\":" docs.json; then
              sed -i "/\"$key\": \[/a\    \"$url\"," docs.json
            else
              if [[ $first -eq 0 ]]; then
                echo "," >> docs.json
              fi
              echo "  \"$key\": [" >> docs.json
              echo "    \"$url\"" >> docs.json
              echo "  ]" >> docs.json
              first=0
            fi
          done
          echo "}" >> docs.json

      - name: Commit docs.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-generate full docs.json"
          file_pattern: docs.json
