name: Generate docs.json

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate docs.json
        run: |
          echo '{' > docs.json
          for dir in sem3/*; do
            if [ -d "$dir" ]; then
              subject=$(basename "$dir")
              echo "  \"$subject\": [" >> docs.json
              for file in "$dir"/*; do
                fname=$(basename "$file")
                echo "    \"https://harnitya29.github.io/sem3/$subject/$fname\"," >> docs.json
              done
              sed -i '$ s/,$//' docs.json
              echo "  ]," >> docs.json
            fi
          done
          sed -i '$ s/,$//' docs.json
          echo '}' >> docs.json

      - name: Commit docs.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-generate docs.json"
          file_pattern: 'docs.json'
