name: Generate full docs.json

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate docs.json recursively
        run: |
          echo '{' > docs.json
          first=1
          while IFS= read -r -d '' file; do
            relpath="${file#./}"
            dirname=$(dirname "$relpath")
            filename=$(basename "$file")
            url="https://harnitya29.github.io/sem3/$relpath"
            key="${dirname//\//_}"
            if [[ $first -eq 1 ]]; then
              echo "  \"$key\": [\"$url\"" >> docs.json
              first=0
            else
              if grep -q "\"$key\":" docs.json; then
                sed -i "/\"$key\": \[/a\ \ \"$url\"," docs.json
              else
                echo "  ,\"$key\": [\"$url\"" >> docs.json
              fi
            fi
          done < <(find . -type f \\( -name '*.pdf' -o -name '*.ppt' -o -name '*.pptx' \\) -print0)
          sed -i 's/,$//' docs.json
          echo "  ]" >> docs.json
          echo '}' >> docs.json

      - name: Commit docs.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-generate full docs.json"
          file_pattern: docs.json
